<a href="https://colab.research.google.com/github/kisBelus/Machine-Learning/blob/master/HW_4/Homework_4_Problem_1_and_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Convolution Function


In [0]:
def conv2d (input_mat, kernel_mat):
  #Dimensions of inputs
  input_width = input_mat.shape[1]
  input_height = input_mat.shape[0]
  kernel_width = kernel_mat.shape[1]
  kernel_height = kernel_mat.shape[0]

  if input_width < kernel_width or input_height < kernel_height:
    raise Exception('Kernel should not be larger than the input matrix')
  if input_width != input_height or kernel_width != kernel_height:
    raise Exception('Matrix is not square')

  #Number of lateral and vertical steps the convolution will take
  steps = input_width-kernel_width+1

  output_mat = np.empty((steps,steps), dtype=int)

  #Convolution Loop
  y_pos = 0
  while y_pos< steps:
    x_pos = 0
    while x_pos< steps:
      y_conv_pos = 0
      output_val = 0
      while y_conv_pos<kernel_height:
        x_conv_pos = 0
        while x_conv_pos<kernel_width:
          input_cel = input_mat[y_pos + y_conv_pos].item(x_pos + x_conv_pos)
          kernel_cel = kernel_mat[y_conv_pos].item(x_conv_pos)
          output_val +=  input_cel * kernel_cel 
          x_conv_pos+=1
        y_conv_pos+=1
      output_mat[y_pos][x_pos] = output_val
      
      x_pos+=1  
    y_pos+=1
    
  return output_mat


#Convolution Demo

In [10]:
input_matrix = np.matrix('1 2 3 4 5 6;6 5 4 3 2 1;4 5 6 7 8 9;9 8 7 6 5 4;0 1 2 3 4 5; 5 4 3 2 1 0')
kernel_matrix = np.matrix('1 0 1; 0 1 0; 1 0 1')
k_mat = np.matrix(' 0 0 0; 0 1 0; 0 0 0')
print("input:\n", input_matrix)
print("Kernel:\n",kernel_matrix)

output = conv2d(input_matrix, k_mat)
print("\n\nOutput:\n",output)

input:
 [[1 2 3 4 5 6]
 [6 5 4 3 2 1]
 [4 5 6 7 8 9]
 [9 8 7 6 5 4]
 [0 1 2 3 4 5]
 [5 4 3 2 1 0]]
Kernel:
 [[1 0 1]
 [0 1 0]
 [1 0 1]]


Output:
 [[5 4 3 2]
 [5 6 7 8]
 [8 7 6 5]
 [1 2 3 4]]


#Max Pooling Function


In [0]:
def maxpooling2d (input_mat, s):
  #Input dimensions
  input_width = input_mat.shape[1]
  input_height = input_mat.shape[0]

  
  if input_width < s or input_height < s:
    raise Exception('s should not be larger than the input matrix')
  if input_width != input_height:
    raise Exception('Matrix is not square')

  output_mat = np.empty((int(input_width/s),int(input_height/s)), dtype=int)
  
  #Maxpool loop
  y_pos = 0
  out_x = 0
  out_y = 0
  while y_pos<=input_height-s:
    x_pos = 0
    out_x = 0
    while x_pos<=input_width-s:
      max_val = 0
      y_pool = 0
      while y_pool < s:
        x_pool = 0
        while x_pool < s:
          if input_mat[y_pos+y_pool].item(x_pos+x_pool) > max_val:
            max_val = input_mat[y_pos+y_pool].item(x_pos+x_pool)
          x_pool+=1
        y_pool+=1
      output_mat[out_y][out_x] = max_val  

      out_x+= 1
      x_pos+= s
    out_y+= 1
    y_pos+= s
  return output_mat

#Maxpool Demo

In [14]:
maxpool = maxpooling2d(input_matrix, 2)
print(maxpool)

[[6 4 6]
 [9 7 9]
 [5 3 5]]
